Server:
  Address: 127.0.0.1:8080 # 服务监听端口
  Debug: false
Smtp: # SMTP配置
  Host: smtp.example.com
  Port: 465
  Secure: true
  Username: username
  Password: password
  SenderEmail: email@example.com
  SenderName: Example
BlogInfo:
  Title: Blog Title
  BlogAddress: https://blog.example.com
  AuthorEmail: contact@example.com       # 博主邮箱 用于接受用户评论
Safety:
  Whitelist:                             # 请求白名单
    - 1.1.1.1
    - 1.2.3.4
Redis:                                   # 利用 Redis 实现的 消息队列, 用于控制发信频率
  Enable: true                           # 是否启用
  Address: 127.0.0.1:6379
  Database: 0
  Password:
  Prefix: waline:mail                    # Redis Key 前缀
  Concurrency: 2                         # 允许的最大并发数量